apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-admin
  label: jenkins-agent
  containers:
    - name: gcloud
      image: gcr.io/cloud-builders/gcloud
      command: ['cat']
      tty: true
    - name: kubectl
      image: gcr.io/cloud-builders/kubectl
      command: ['cat']
      tty: true
